^ This is XLogger

Sick of the *B* word? So are we! Become an xlogger today. 

XLogging is about refining your ideas over time. It's for people who like to write and people who like to read. Think of your thoughts and passions as wiki pages, that only you can edit, but that you can revise over time instead of having to say it all at once.

Think it. Write it. Push it. Reload it. Fuck it, dude. Let's go bowling.

That's xlogging.

Just remember: _You don't *talk* about xlog!_
